/*
 * adc.c
 *
 * Stage 3 supports independent software-triggered static monitoring.
 * From Stage 5 onward the ADC must be triggered by ePWM1 SOCA for fixed
 * phase sampling; Stage 6 closed loop must not use asynchronous timer ADC.
 */

#include "DSP2803x_Device.h"
#include "DSP2803x_Examples.h"
#include "llc_config.h"
#include "llc_globals.h"
#include "adc.h"
#include "shot.h"

#define ADC_ACQPS     7U
#define ADC_SOC_MASK  0x0007U   /* SOC0, SOC1, SOC2 */

void ADC_ResetFreshnessBlackbox(void)
{
    g_adc_freshness_wait_first_publish = 0U;
    g_adc_freshness_monitor_armed = 0U;
    g_adc_last_publish_timer2 = 0UL;
    g_control_last_consume_timer2 = 0UL;
    g_adc_stale_total = 0UL;
    g_adc_stale_consecutive_max = 0U;
    g_adc_first_stale_frozen = 0U;
    g_adc_first_stale_phase = 0U;
    g_adc_first_stale_fast_tick = 0UL;
    g_adc_first_stale_timer2 = 0UL;
    g_adc_first_stale_publish_sequence = 0UL;
    g_adc_first_stale_consume_sequence = 0UL;
    g_adc_first_stale_sample_age_cycles = 0UL;
    g_adc_first_stale_consecutive = 0U;
    g_adc_first_stale_intflg = 0U;
    g_adc_first_stale_intovf = 0U;
    g_adc_first_stale_socflg = 0U;
    g_adc_first_stale_socovf = 0U;
    g_adc_first_stale_soca_flag = 0U;
    g_adc_first_stale_soca_enable = 0U;
    g_adc_first_stale_soca_period = 0U;
    g_adc_fault_snapshot_frozen = 0U;
    g_adc_fault_snapshot_phase = 0U;
    g_adc_fault_snapshot_timer2 = 0UL;
    g_adc_fault_snapshot_flags = 0UL;
    g_adc_fault_snapshot_publish_sequence = 0UL;
    g_adc_fault_snapshot_consume_sequence = 0UL;
    g_adc_fault_snapshot_intflg = 0U;
    g_adc_fault_snapshot_intovf = 0U;
    g_adc_fault_snapshot_socflg = 0U;
    g_adc_fault_snapshot_socovf = 0U;
    g_adc_ovf_active_count = 0UL;
}

void ADC_FreezeFirstStale(Uint16 phase)
{
    Uint32 now;
    if (g_adc_first_stale_frozen != 0U) return;
    now = (Uint32)CpuTimer2Regs.TIM.all;
    g_adc_first_stale_frozen = 1U;
    g_adc_first_stale_phase = phase;
    g_adc_first_stale_fast_tick = g_fast_tick;
    g_adc_first_stale_timer2 = now;
    g_adc_first_stale_publish_sequence = g_adc_sample_sequence;
    g_adc_first_stale_consume_sequence = g_control_adc_sequence_consumed;
    g_adc_first_stale_sample_age_cycles = (g_adc_last_publish_timer2 == 0UL)
        ? 0xFFFFFFFFUL
        : (Uint32)((g_adc_last_publish_timer2 - now) & 0xFFFFFFFFUL);
    g_adc_first_stale_consecutive = g_shot_summary.consecutive_stale_count;
    g_adc_first_stale_intflg = AdcRegs.ADCINTFLG.all;
    g_adc_first_stale_intovf = AdcRegs.ADCINTOVF.all;
    g_adc_first_stale_socflg = AdcRegs.ADCSOCFLG1.all;
    g_adc_first_stale_socovf = AdcRegs.ADCSOCOVF1.all;
    g_adc_first_stale_soca_flag = EPwm1Regs.ETFLG.bit.SOCA;
    g_adc_first_stale_soca_enable = EPwm1Regs.ETSEL.bit.SOCAEN;
    g_adc_first_stale_soca_period = EPwm1Regs.ETPS.bit.SOCAPRD;
}

void ADC_FreezeFaultSnapshot(void)
{
    if (g_adc_fault_snapshot_frozen != 0U) return;
    g_adc_fault_snapshot_frozen = 1U;
    g_adc_fault_snapshot_phase = g_pipeline_phase;
    g_adc_fault_snapshot_timer2 = (Uint32)CpuTimer2Regs.TIM.all;
    g_adc_fault_snapshot_flags = g_fault_flags | FAULT_ADC_STALE_OVERFLOW;
    g_adc_fault_snapshot_publish_sequence = g_adc_sample_sequence;
    g_adc_fault_snapshot_consume_sequence = g_control_adc_sequence_consumed;
    g_adc_fault_snapshot_intflg = AdcRegs.ADCINTFLG.all;
    g_adc_fault_snapshot_intovf = AdcRegs.ADCINTOVF.all;
    g_adc_fault_snapshot_socflg = AdcRegs.ADCSOCFLG1.all;
    g_adc_fault_snapshot_socovf = AdcRegs.ADCSOCOVF1.all;
}

static void ADC_ConfigureSocs(Uint16 trigsel)
{
    AdcRegs.ADCSOC0CTL.bit.CHSEL  = 1U;   /* ADCINA1 = Vout */
    AdcRegs.ADCSOC0CTL.bit.ACQPS  = ADC_ACQPS;
    AdcRegs.ADCSOC0CTL.bit.TRIGSEL = trigsel;

    AdcRegs.ADCSOC1CTL.bit.CHSEL  = 2U;   /* ADCINA2 / COMP1A = Ipri */
    AdcRegs.ADCSOC1CTL.bit.ACQPS  = ADC_ACQPS;
    AdcRegs.ADCSOC1CTL.bit.TRIGSEL = trigsel;

    AdcRegs.ADCSOC2CTL.bit.CHSEL  = 3U;   /* ADCINA3 = Iout */
    AdcRegs.ADCSOC2CTL.bit.ACQPS  = ADC_ACQPS;
    AdcRegs.ADCSOC2CTL.bit.TRIGSEL = trigsel;
}

void ADC_Init(void)
{
    /* Device support powers up ADC and waits for analog settle. */
    InitAdc();

    EALLOW;
    AdcRegs.ADCCTL2.bit.ADCNONOVERLAP = 1U;
    AdcRegs.ADCCTL2.bit.CLKDIV2EN = 0U;
    AdcRegs.SOCPRICTL.bit.ONESHOT = 0U;
    AdcRegs.SOCPRICTL.bit.SOCPRIORITY = 0U;

    /* ADCINT1 is generated by EOC2 (last of the three conversions). */
    AdcRegs.INTSEL1N2.bit.INT1SEL  = 2U;
    AdcRegs.INTSEL1N2.bit.INT1E    = 1U;
    AdcRegs.INTSEL1N2.bit.INT1CONT = 0U;
    AdcRegs.ADCINTFLGCLR.all = 0xFFFFU;
    AdcRegs.ADCINTOVFCLR.all = 0xFFFFU;

    ADC_ConfigureSocs(0U);   /* default software trigger */
    EDIS;
}

void ADC_SetSoftwareTriggerMode(void)
{
    EALLOW;
    ADC_ConfigureSocs(0U);
    AdcRegs.INTSEL1N2.bit.INT1CONT = 0U;
    EPwm1Regs.ETSEL.bit.SOCAEN = 0U;
    EDIS;
    g_adc_trigger_mode = 0U;
}

void ADC_SetPwmSyncTriggerMode(void)
{
    EALLOW;
    ADC_ConfigureSocs(5U);   /* ePWM1 SOCA */
    AdcRegs.INTSEL1N2.bit.INT1CONT = 0U;
    EPwm1Regs.ETSEL.bit.SOCASEL = ET_CTR_ZERO;
    EPwm1Regs.ETSEL.bit.SOCAEN  = 1U;
    EPwm1Regs.ETPS.bit.SOCAPRD  = ET_1ST;
    AdcRegs.ADCINTOVFCLR.all = 0xFFFFU;
    AdcRegs.ADCINTFLGCLR.all = 0xFFFFU;
    EDIS;
    g_adc_trigger_mode = 1U;
}

/*
 * ADC_SetClosedLoopSyncTriggerMode
 *
 * STAGE6_CLOSED_LOOP_HANDOFF: closed-loop ADC sampling. SOCA still comes from
 * the CMPB fixed-phase point (kept by ADC_UpdatePwmSyncPoint), but the sample
 * is taken every 3rd PWM period (SOCAPRD = ET_3RD). This yields:
 *     120 kHz switching -> ~40 kS/s
 *     150 kHz switching -> ~50 kS/s
 *     180 kHz switching -> ~60 kS/s
 * which matches the 20 us / 50 kHz control tick. The SoftStart ramp keeps
 * ET_1ST (ADC_SetPwmSyncTriggerMode / ADC_UpdatePwmSyncPoint); only the
 * closed-loop path calls this.
 */
void ADC_SetClosedLoopSyncTriggerMode(void)
{
    EALLOW;
    ADC_ConfigureSocs(5U);           /* ePWM1 SOCA */
    /* Closed loop is a continuous event stream. Generate an ADCINT1 pulse for
     * every completed EOC2 frame even if a preceding flag is still pending;
     * the ISR entry clear below then preserves any later event. */
    AdcRegs.INTSEL1N2.bit.INT1CONT = 1U;
    EPwm1Regs.ETSEL.bit.SOCASEL = ET_CTRU_CMPB;   /* fixed-phase CMPB point */
    EPwm1Regs.ETSEL.bit.SOCAEN  = 1U;
    EPwm1Regs.ETPS.bit.SOCAPRD  = ET_3RD;         /* every 3rd PWM period */
    AdcRegs.ADCINTOVFCLR.all = 0xFFFFU;
    AdcRegs.ADCINTFLGCLR.all = 0xFFFFU;
    EDIS;
    g_adc_trigger_mode = 1U;
}

void ADC_SoftwareTrigger(void)
{
    EALLOW;
    AdcRegs.ADCSOCFRC1.all = ADC_SOC_MASK;
    EDIS;
}

/*
 * ADC_UpdatePwmSyncPoint
 *
 * Moves the ePWM1 SOCA VOUT sampling point to the midpoint of the current
 * switching period. Call whenever TBPRD changes during a diagnostic run.
 * Does not enable ADC CPU interrupt; ADCINT1 flag is used as a hardware
 * conversion-complete evidence while PIE Group1 remains masked.
 */
void ADC_UpdatePwmSyncPoint(Uint16 period)
{
    Uint16 cmpa;
    Uint16 sample_cmpb;

    /* Sample at approximately 25% of the period, away from the CMPA
     * switching edge. CMPB = CMPA / 2. */
    cmpa = (Uint16)((period + 1U) / 2U);
    sample_cmpb = (Uint16)(cmpa / 2U);

    EALLOW;
    EPwm1Regs.CMPB = sample_cmpb;
    EPwm1Regs.ETSEL.bit.SOCASEL = ET_CTRU_CMPB;
    EPwm1Regs.ETPS.bit.SOCAPRD = ET_1ST;
    EPwm1Regs.ETCLR.bit.SOCA = 1U;
    EPwm1Regs.ETSEL.bit.SOCAEN = 1U;
    EDIS;

    g_adc_pwm_sync_cmpb = sample_cmpb;
    g_adc_pwm_sync_cmpa = cmpa;
    g_adc_pwm_sync_edge_distance = (Uint16)(cmpa - sample_cmpb);
}

/*
 * ADC_UpdatePwmSyncPointKeepCadence
 *
 * Like ADC_UpdatePwmSyncPoint but preserves the current SOCAPRD cadence
 * (e.g. ET_3RD in closed loop). Re-positions the CMPB VOUT sampling point to
 * the midpoint of the new switching period WITHOUT resetting the sampling
 * cadence to every-period (ET_1ST). Used by the real LLC actuator so that a
 * dynamic frequency change keeps both the ADC phase (CMPB) and the cadence
 * (ET_3RD) correct.
 */
void ADC_UpdatePwmSyncPointKeepCadence(Uint16 period)
{
    Uint16 cmpa;
    Uint16 sample_cmpb;

    cmpa = (Uint16)((period + 1U) / 2U);
    sample_cmpb = (Uint16)(cmpa / 2U);

    EALLOW;
    EPwm1Regs.CMPB = sample_cmpb;
    EPwm1Regs.ETSEL.bit.SOCASEL = ET_CTRU_CMPB;
    EPwm1Regs.ETCLR.bit.SOCA = 1U;
    EPwm1Regs.ETSEL.bit.SOCAEN = 1U;
    EDIS;

#if !STAGE6_FIRST_BOUNDED_REAL_PI_SHOT
    g_adc_pwm_sync_cmpb = sample_cmpb;
    g_adc_pwm_sync_cmpa = cmpa;
    g_adc_pwm_sync_edge_distance = (Uint16)(cmpa - sample_cmpb);
#endif
}

void ADC_CheckOverflow(void)
{
    EALLOW;
    if (AdcRegs.ADCINTOVF.all != 0U)
    {
        /* In non-continuous modes an overflow suppresses the next interrupt
         * and is therefore a real stale-chain fault. Closed-loop INT1CONT=1
         * still emits every EOC2 pulse; overlap is retained as telemetry while
         * the unchanged sequence monitor owns true stopped-publication faults. */
        if (g_no_energy_test_mode == 0U &&
            AdcRegs.INTSEL1N2.bit.INT1CONT == 0U)
        {
            g_fault_flags |= FAULT_ADC_STALE_OVERFLOW;
            g_fault_history |= FAULT_ADC_STALE_OVERFLOW;
            ADC_FreezeFaultSnapshot();
        }
        AdcRegs.ADCINTOVFCLR.all = 0xFFFFU;
    }
    EDIS;
}

__interrupt void ADCINT1_ISR(void)
{
    Uint16 adc_ovf_at_entry;
    Uint16 first_publish_pending_at_entry;
#if STAGE6_ON_TARGET_SHADOW_NOENERGY_TEST
    Uint32 adc_t_entry, adc_t_exit;
    if (g_stage6_noenergy_test_enable != 0U)
    {
        adc_t_entry = CpuTimer2Regs.TIM.all;
        g_stage6_adc_isr_count++;
    }
#endif
    Uint16 vout = AdcResult.ADCRESULT0;
    Uint16 ipri = AdcResult.ADCRESULT1;
    Uint16 iout = AdcResult.ADCRESULT2;

    /* SOL W1 root-cause fix: the old ISR held ADCINT1 asserted through the
     * complete filter/telemetry body. At 170 kHz / ET_3RD, a deferred ADC ISR
     * could still have the flag set when the next EOC2 arrived, latching
     * ADCINTOVF and stopping the real shot. Snapshot overflow first, then clear
     * ADCINT1 immediately after the completed frame is copied. A new EOC2 that
     * arrives during this ISR remains pending for the next group-1 dispatch;
     * there is deliberately no second flag clear at ISR exit. */
    EALLOW;
    first_publish_pending_at_entry = g_adc_freshness_wait_first_publish;
    adc_ovf_at_entry = AdcRegs.ADCINTOVF.all;
    AdcRegs.ADCINTFLGCLR.bit.ADCINT1 = 1U;
    EDIS;

    /* STAGE6 closed-loop no-energy: inject a synthetic Vout VALUE while the
     * real ADC cadence (sequence advance, filter, OVF) stays fully authentic.
     * Used only by the on-target no-energy harness so the closed-loop PI sees
     * a controlled sample (e.g. ~10V at the first post-handoff sample). */
#if STAGE6_ON_TARGET_SHADOW_NOENERGY_TEST
    if (g_stage6_closeloop_vout_inject != 0U)
    {
        vout = g_stage6_synthetic_vout_raw;
    }
#endif

    g_adc_vout_raw = vout;
    g_adc_ipri_raw = ipri;
    g_adc_iout_raw = iout;

    /*
     * 1/16 IIR low-pass. The accumulator is kept in 16x format internally.
     * The CCS-facing filtered_raw is normalized to the same scale as raw:
     *   filtered_raw = acc >> 4
     * The accumulator is also exposed for debugging (Plan A).
     */
    g_adc_vout_filter_acc = g_adc_vout_filter_acc - (g_adc_vout_filter_acc >> 4) + vout;
    g_adc_ipri_filter_acc = g_adc_ipri_filter_acc - (g_adc_ipri_filter_acc >> 4) + ipri;
    g_adc_iout_filter_acc = g_adc_iout_filter_acc - (g_adc_iout_filter_acc >> 4) + iout;

    g_adc_vout_filtered_raw = (Uint16)(g_adc_vout_filter_acc >> 4);
    g_adc_ipri_filtered_raw = (Uint16)(g_adc_ipri_filter_acc >> 4);
    g_adc_iout_filtered_raw = (Uint16)(g_adc_iout_filter_acc >> 4);

    g_adc_sample_counter++;
    g_adc_sample_sequence++;
    g_adc_last_publish_timer2 = (Uint32)CpuTimer2Regs.TIM.all;
    if (g_adc_freshness_wait_first_publish != 0U)
    {
        g_adc_freshness_wait_first_publish = 0U;
        g_adc_freshness_monitor_armed = 1U;
    }
    g_adc_isr_last_tbctr = EPwm1Regs.TBCTR;

    /* Stage 4D power probe peak capture */
    if (g_power_probe_active != 0U)
    {
        if (g_adc_ipri_raw > g_power_probe_adc_ipri_peak)
        {
            g_power_probe_adc_ipri_peak = g_adc_ipri_raw;
        }
    }

    EALLOW;
    if (adc_ovf_at_entry != 0U || AdcRegs.ADCINTOVF.all != 0U)
    {
        g_adc_ovf_count++;
        if (first_publish_pending_at_entry == 0U)
            g_adc_ovf_active_count++;
        if (g_adc_ovf_first_tbctr == 0U)
        {
            g_adc_ovf_first_tbctr = EPwm1Regs.TBCTR;
            g_adc_ovf_first_flag_was_set = AdcRegs.ADCINTFLG.bit.ADCINT1;
        }
        /* During the formal ramp FastUpdate's SOCA discipline owns freshness
         * and the ADCINT1 vector is disabled; OVF here is a benign conversion
         * timing race, not a fault of the ramp itself. */
        if (g_no_energy_test_mode == 0U && g_softstart_ramp_active == 0U &&
            AdcRegs.INTSEL1N2.bit.INT1CONT == 0U &&
            first_publish_pending_at_entry == 0U)
        {
            g_fault_flags |= FAULT_ADC_STALE_OVERFLOW;
            g_fault_history |= FAULT_ADC_STALE_OVERFLOW;
            ADC_FreezeFaultSnapshot();
        }
        AdcRegs.ADCINTOVFCLR.all = 0xFFFFU;
    }

    EDIS;
    PieCtrlRegs.PIEACK.all = PIEACK_GROUP1;

#if STAGE6_ON_TARGET_SHADOW_NOENERGY_TEST
    if (g_stage6_noenergy_test_enable != 0U)
    {
        adc_t_exit = CpuTimer2Regs.TIM.all;
        g_adc_isr_cycles_last = (Uint32)((Uint32)(adc_t_entry - adc_t_exit) & 0xFFFFFFFFUL);
        if (g_adc_isr_cycles_last > g_adc_isr_cycles_max)
            g_adc_isr_cycles_max = g_adc_isr_cycles_last;
        g_adc_isr_cycles_sum += g_adc_isr_cycles_last;
        g_adc_isr_cycles_count++;
    }
#endif
}
