/*
 * adc.c
 *
 * Stage 3 supports independent software-triggered static monitoring.
 * From Stage 5 onward the ADC must be triggered by ePWM1 SOCA for fixed
 * phase sampling; Stage 6 closed loop must not use asynchronous timer ADC.
 */

#include "DSP2803x_Device.h"
#include "DSP2803x_Examples.h"
#include "llc_config.h"
#include "llc_globals.h"
#include "adc.h"

#define ADC_ACQPS     7U
#define ADC_SOC_MASK  0x0007U   /* SOC0, SOC1, SOC2 */

static void ADC_ConfigureSocs(Uint16 trigsel)
{
    AdcRegs.ADCSOC0CTL.bit.CHSEL  = 1U;   /* ADCINA1 = Vout */
    AdcRegs.ADCSOC0CTL.bit.ACQPS  = ADC_ACQPS;
    AdcRegs.ADCSOC0CTL.bit.TRIGSEL = trigsel;

    AdcRegs.ADCSOC1CTL.bit.CHSEL  = 2U;   /* ADCINA2 / COMP1A = Ipri */
    AdcRegs.ADCSOC1CTL.bit.ACQPS  = ADC_ACQPS;
    AdcRegs.ADCSOC1CTL.bit.TRIGSEL = trigsel;

    AdcRegs.ADCSOC2CTL.bit.CHSEL  = 3U;   /* ADCINA3 = Iout */
    AdcRegs.ADCSOC2CTL.bit.ACQPS  = ADC_ACQPS;
    AdcRegs.ADCSOC2CTL.bit.TRIGSEL = trigsel;
}

void ADC_Init(void)
{
    /* Device support powers up ADC and waits for analog settle. */
    InitAdc();

    EALLOW;
    AdcRegs.ADCCTL2.bit.ADCNONOVERLAP = 1U;
    AdcRegs.ADCCTL2.bit.CLKDIV2EN = 0U;
    AdcRegs.SOCPRICTL.bit.ONESHOT = 0U;
    AdcRegs.SOCPRICTL.bit.SOCPRIORITY = 0U;

    /* ADCINT1 is generated by EOC2 (last of the three conversions). */
    AdcRegs.INTSEL1N2.bit.INT1SEL  = 2U;
    AdcRegs.INTSEL1N2.bit.INT1E    = 1U;
    AdcRegs.INTSEL1N2.bit.INT1CONT = 0U;
    AdcRegs.ADCINTFLGCLR.all = 0xFFFFU;
    AdcRegs.ADCINTOVFCLR.all = 0xFFFFU;

    ADC_ConfigureSocs(0U);   /* default software trigger */
    EDIS;
}

void ADC_SetSoftwareTriggerMode(void)
{
    EALLOW;
    ADC_ConfigureSocs(0U);
    EPwm1Regs.ETSEL.bit.SOCAEN = 0U;
    EDIS;
    g_adc_trigger_mode = 0U;
}

void ADC_SetPwmSyncTriggerMode(void)
{
    EALLOW;
    ADC_ConfigureSocs(5U);   /* ePWM1 SOCA */
    EPwm1Regs.ETSEL.bit.SOCASEL = ET_CTR_ZERO;
    EPwm1Regs.ETSEL.bit.SOCAEN  = 1U;
    EPwm1Regs.ETPS.bit.SOCAPRD  = ET_1ST;
    AdcRegs.ADCINTOVFCLR.all = 0xFFFFU;
    AdcRegs.ADCINTFLGCLR.all = 0xFFFFU;
    EDIS;
    g_adc_trigger_mode = 1U;
}

void ADC_SoftwareTrigger(void)
{
    EALLOW;
    AdcRegs.ADCSOCFRC1.all = ADC_SOC_MASK;
    EDIS;
}

/*
 * ADC_UpdatePwmSyncPoint
 *
 * Moves the ePWM1 SOCA VOUT sampling point to the midpoint of the current
 * switching period. Call whenever TBPRD changes during a diagnostic run.
 * Does not enable ADC CPU interrupt; ADCINT1 flag is used as a hardware
 * conversion-complete evidence while PIE Group1 remains masked.
 */
void ADC_UpdatePwmSyncPoint(Uint16 period)
{
    Uint16 cmpa;
    Uint16 sample_cmpb;

    /* Sample at approximately 25% of the period, away from the CMPA
     * switching edge. CMPB = CMPA / 2. */
    cmpa = (Uint16)((period + 1U) / 2U);
    sample_cmpb = (Uint16)(cmpa / 2U);

    EALLOW;
    EPwm1Regs.CMPB = sample_cmpb;
    EPwm1Regs.ETSEL.bit.SOCASEL = ET_CTRU_CMPB;
    EPwm1Regs.ETPS.bit.SOCAPRD = ET_1ST;
    EPwm1Regs.ETCLR.bit.SOCA = 1U;
    EPwm1Regs.ETSEL.bit.SOCAEN = 1U;
    EDIS;

    g_adc_pwm_sync_cmpb = sample_cmpb;
    g_adc_pwm_sync_cmpa = cmpa;
    g_adc_pwm_sync_edge_distance = (Uint16)(cmpa - sample_cmpb);
}

void ADC_CheckOverflow(void)
{
    if (AdcRegs.ADCINTOVF.all != 0U)
    {
        if (g_no_energy_test_mode == 0U)
        {
            g_fault_flags |= FAULT_ADC_STALE_OVERFLOW;
            g_fault_history |= FAULT_ADC_STALE_OVERFLOW;
        }
        AdcRegs.ADCINTOVFCLR.all = 0xFFFFU;
    }
}

__interrupt void ADCINT1_ISR(void)
{
    Uint16 vout = AdcResult.ADCRESULT0;
    Uint16 ipri = AdcResult.ADCRESULT1;
    Uint16 iout = AdcResult.ADCRESULT2;

    g_adc_vout_raw = vout;
    g_adc_ipri_raw = ipri;
    g_adc_iout_raw = iout;

    /*
     * 1/16 IIR low-pass. The accumulator is kept in 16x format internally.
     * The CCS-facing filtered_raw is normalized to the same scale as raw:
     *   filtered_raw = acc >> 4
     * The accumulator is also exposed for debugging (Plan A).
     */
    g_adc_vout_filter_acc = g_adc_vout_filter_acc - (g_adc_vout_filter_acc >> 4) + vout;
    g_adc_ipri_filter_acc = g_adc_ipri_filter_acc - (g_adc_ipri_filter_acc >> 4) + ipri;
    g_adc_iout_filter_acc = g_adc_iout_filter_acc - (g_adc_iout_filter_acc >> 4) + iout;

    g_adc_vout_filtered_raw = (Uint16)(g_adc_vout_filter_acc >> 4);
    g_adc_ipri_filtered_raw = (Uint16)(g_adc_ipri_filter_acc >> 4);
    g_adc_iout_filtered_raw = (Uint16)(g_adc_iout_filter_acc >> 4);

    g_adc_sample_counter++;
    g_adc_sample_sequence++;

    /* Stage 4D power probe peak capture */
    if (g_power_probe_active != 0U)
    {
        if (g_adc_ipri_raw > g_power_probe_adc_ipri_peak)
        {
            g_power_probe_adc_ipri_peak = g_adc_ipri_raw;
        }
    }

    if (AdcRegs.ADCINTOVF.all != 0U)
    {
        if (g_no_energy_test_mode == 0U)
        {
            g_fault_flags |= FAULT_ADC_STALE_OVERFLOW;
            g_fault_history |= FAULT_ADC_STALE_OVERFLOW;
        }
        AdcRegs.ADCINTOVFCLR.all = 0xFFFFU;
    }

    AdcRegs.ADCINTFLGCLR.bit.ADCINT1 = 1U;
    PieCtrlRegs.PIEACK.all = PIEACK_GROUP1;
}
