#ifndef BURST_REGION_H_
#define BURST_REGION_H_

/* W2_CONTROL_REGION_REDESIGN_V1 - Burst region state model.
 *
 * PHASE 1 SCOPE (work order section 5): design + host/NE model + no-energy
 * verification ONLY. This module is compiled ONLY into the NE harness build
 * (tools/build_open_loop_steady_noenergy.bat); the production REAL build does
 * not include it and no REAL Burst firing happens in this work order.
 *
 * Region principle (work order sections 1/2/7): Burst entry is generated by
 * Fmax saturation + voltage error, NEVER by a load ID or an absolute Vout
 * value:
 *   burst_entry_candidate =
 *       (freq_command >= FMAX)
 *    && (vout > vref + V_ENTRY_HYST)
 *    && (condition sustained N fresh samples)
 * plus hysteresis, persistence/debounce and a minimum RUN dwell.
 * Vref is generic (10 V / 12 V / 15 V) - no hard-coded 10 V anywhere.
 */

#include "DSP2803x_Device.h"

#if STAGE6_OPEN_LOOP_STEADY_BUILD && STAGE6_ON_TARGET_SHADOW_NOENERGY_TEST

#define BR_STATE_IDLE        0U
#define BR_STATE_RUN_PFM     1U
#define BR_STATE_BURST_PREP  2U
#define BR_STATE_BURST_ON    3U
#define BR_STATE_BURST_OFF   4U
#define BR_STATE_FAULT       5U

extern volatile Uint16 g_br_enable;              /* module enable (NE) */
extern volatile Uint16 g_br_state;               /* BR_STATE_* */

/* generic references / plant feedback (NE: host-written synthetic) */
extern volatile Uint16 g_br_vref_raw;
extern volatile Uint16 g_br_vout_raw;
extern volatile Uint16 g_br_vout_rising;         /* dVout/dt > 0 flag (handoff eval) */

/* frequency authority (NE: host-written; REAL binding = the frozen Fmax) */
extern volatile Uint32 g_br_freq_command_hz;
extern volatile Uint32 g_br_fmax_hz;

/* entry / exit shaping */
extern volatile Uint16 g_br_v_entry_hyst_raw;    /* entry band above vref */
extern volatile Uint16 g_br_v_exit_hyst_raw;     /* packet band below vref */
extern volatile Uint16 g_br_entry_persist_n;     /* fresh samples required */
extern volatile Uint16 g_br_min_run_dwell_ticks; /* min RUN_PFM dwell */
extern volatile Uint16 g_br_run_pfm_return_n;    /* freq<Fmax sustained -> back */

/* packet definition (v1: ONE main variable; fixed safe frequency) */
extern volatile Uint16 g_br_packet_cycles;       /* packet length (NE: ticks) */
extern volatile Uint32 g_br_packet_freq_hz;      /* safe fixed packet frequency */

/* one-shot handoff evaluation request (SOFTSTART end -> RUN_PFM or Burst) */
extern volatile Uint16 g_br_handoff_request;

/* NE actuator gate (register writes stay behind it; counters-only in v1) */
extern volatile Uint16 g_br_arm;

/* telemetry */
extern volatile Uint16 g_br_packets_emitted;
extern volatile Uint16 g_br_entry_debounce_rejects;
extern volatile Uint16 g_br_persist_max;         /* live persistence accumulation */
extern volatile Uint16 g_br_packet_ticks_left;
extern volatile Uint16 g_br_coast_ticks;
extern volatile Uint16 g_br_run_ticks;
extern volatile Uint32 g_br_last_entry_vout_raw;
extern volatile Uint32 g_br_tick_count;

void BR_Init(void);
void BR_NeTick(void);

#endif /* STAGE6_OPEN_LOOP_STEADY_BUILD && STAGE6_ON_TARGET_SHADOW_NOENERGY_TEST */

#endif /* BURST_REGION_H_ */